// <auto-generated />
namespace IsasWebPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsasWebPortalIsasWebPortalModelsIsasWebPortalDataContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsasWebPortalIsasWebPortalModelsIsasWebPortalDataContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201601291856280_IsasWebPortal.IsasWebPortal.Models.IsasWebPortalDataContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
